main.o: probando.cpp tipoT.cpp ListaOrd.cpp Pila.cpp Deposito.cpp Cola.h tipoT.h Cola.h ListaOrd.h Pila.h Deposito.h
	g++ probando.cpp tipoT.cpp Cola.cpp ListaOrd.cpp Pila.cpp Deposito.cpp -o Programa 
