main.o: probando.cpp tipoT.cpp ListaOrd.cpp Pila.cpp Deposito.cpp OperacionesDeposito.cpp Cola.h tipoT.h Cola.h ListaOrd.h Pila.h Deposito.h OperacionesDeposito.h
	g++ probando.cpp tipoT.cpp Cola.cpp ListaOrd.cpp Pila.cpp Deposito.cpp OperacionesDeposito.cpp -o Programa 

limpieza: pruebaTAD.cpp tipoT.cpp ListaOrd.cpp Pila.cpp Deposito.cpp OperacionesDeposito.cpp Cola.h tipoT.h Cola.h ListaOrd.h Pila.h Deposito.h OperacionesDeposito.h
	g++ pruebaTAD.cpp tipoT.cpp Cola.cpp ListaOrd.cpp Pila.cpp Deposito.cpp OperacionesDeposito.cpp -o limpieza 
